name: GitHub Actions - AWS EC2 Configure Access
## on: [push]
on:
####----------------------------------------------------------------------------
  workflow_dispatch:
    name: 'Manual Deployment'
    description: 'Triggering Manual Deployment'
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Configure Access'
####----------------------------------------------------------------------------
  push:
    branches: [ master ]
    paths: 
      - action.yaml
####----------------------------------------------------------------------------
env:
  ## Access KeyPair variables
  PRIVATE_KEYPAIR_FILE: .ssh/id_rsa
  PRIVATE_KEYPAIR_SECRET: ${{ secrets.PRIVATE_KEYPAIR_SECRET }}
####----------------------------------------------------------------------------
jobs:
  provision-access:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## Privision Access KeyPair
      - name: Provisioning Access
        uses: ./
        id: provision-access
        with:
          private-keypair-file: ${PRIVATE_KEYPAIR_FILE}
          private-keypair-secret: ${PRIVATE_KEYPAIR_SECRET}
        continue-on-error: false
      - name: Check On Failures
        if: steps.provision-access.outputs.status == 'failure'
        run: |
          echo -e "Warning: Provisioning Access Failed [Status]: ${{ steps.provision-access.outputs.status }}" ;
####----------------------------------------------------------------------------
      ## Display Environment
      - name: Display Environment
        id: display_environment
        run: |
          echo -e "Displaying Enviroment Settings ..." ;
          echo -e "Access KeyPair File: ${PRIVATE_KEYPAIR_FILE}" ;
          echo -e "Access KeyPair Secret: ${PRIVATE_KEYPAIR_SECRET}" ;
