name: GitHub Actions - AWS STS Assume Role
## on: [push]
on:
  push:
    branches: [ master ]
    paths: 
      - action.yaml
####----------------------------------------------------------------------------
env:
  awscli_download: 'awscli.amazonaws.com'
  awscli_package: "awscli-exe-linux-x86_64.zip"
  ## AWS Enviroment variables
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  ## AWS Default variables
  AWS_DEFAULT_ACCOUNT: ${{ secrets.AWS_DEFAULT_ACCOUNT }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ## DevOps environment variables
  DEVOPS_ACCOUNT_NAME: ${{ secrets.DEVOPS_ACCOUNT_NAME }}
  DEVOPS_ACCESS_ROLE: ${{ secrets.DEVOPS_ACCESS_ROLE }}
####----------------------------------------------------------------------------
jobs:
  generate-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
####----------------------------------------------------------------------------
      ## Updating AWS CLI (latest)
      - name: Updating AWS CLI (lastest)
        id: update_awscli
        run: |
          aws --version >/dev/null 2>&1 && {
              echo -e >&2 "AWS CLI is Installed ... Ok! ";
              which terraform ;
              aws --version ;
            } ;
          echo -e "Upgrading AWS-CLI to version 2.0.40" ;
          ## https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2-linux.html
          cd /tmp ;
          wget --quiet "https://${awscli_download}/${awscli_package}" \
               --directory-prefix=/tmp/ --output-document=awscliv2.zip ;
          unzip awscliv2.zip 1>/dev/null ;
          ls -l /usr/local/bin/aws ;
          sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update ;
          aws --version ;
####----------------------------------------------------------------------------
      - name: AWS STS Assume Role
        uses: ./
        id: request_credentials
        with:
          session-timestamp: 'DevOpsPipeline--20200827193000'
          aws-default-account: ${{ env.AWS_DEFAULT_ACCOUNT }}
          aws-default-region: ${{ env.AWS_DEFAULT_REGION }}
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          devops-access-role: ${{ env.DEVOPS_ACCESS_ROLE }}
          devops-account-name: ${{ env.DEVOPS_ACCOUNT_NAME }}
####----------------------------------------------------------------------------
      ## Display Environment
      - name: Display Environment
        id: display_environment
        run: |
          echo -e "Displaying Enviroment Settings ..." ;
          echo -e "AWS Access Key-ID: ${AWS_ACCESS_KEY_ID}" ;
          echo -e "AWS Secret Access Key: ${AWS_SECRET_ACCESS_KEY}" ;
          echo -e "AWS Session Token: ${AWS_SESSION_TOKEN}" ;
####----------------------------------------------------------------------------
      ## Display IAM List-Users
      - name: Display IAM List-Users
        id: display_listusers
        run: |
          aws --profile default \
          --region ${AWS_DEFAULT_REGION} \
          iam list-users \
          --query 'Users[?UserName==`'${DEVOPS_ACCOUNT_NAME}'`]' ;
